# Generated by Django 3.2.16 on 2023-02-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000000)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=1000)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
