# Generated by Django 3.2.16 on 2023-03-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_wear', '0006_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('head', 'head'), ('body', 'body'), ('foot', 'foot'), ('equip', 'equip'), ('more', 'more')], max_length=1000),
        ),
    ]
