# Generated by Django 3.2.16 on 2023-05-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_wear', '0011_remove_feedback_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='phone_number',
            field=models.CharField(default='0712345678', max_length=100000),
        ),
    ]
