# Generated by Django 3.2.16 on 2023-05-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety_wear', '0012_products_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
